project:
  type: website
  output-dir: docs

website:
  title: "Intro to Marine Data Science"
  navbar:
    right:
      - text: "PROG"
        menu:
          - tracks/prog/prog101.qmd
          - tracks/prog/prog102.qmd
          - tracks/prog/prog103.qmd
          - tracks/prog/prog104.qmd
          - tracks/prog/prog201.qmd
          - tracks/prog/prog202.qmd
      - text: "PRST"
        menu:
          - tracks/prst/prst101.qmd
          - tracks/prst/prst102.qmd
          - tracks/prst/prst103.qmd
          - tracks/prst/prst104.qmd
          - tracks/prst/prst201.qmd
          - tracks/prst/prst202.qmd
      - text: "INFO"
        menu:
          - tracks/info/info101.qmd
          - tracks/info/info102.qmd
          - tracks/info/info103.qmd
          - tracks/info/info104.qmd
          - tracks/info/info201.qmd
          - tracks/info/info202.qmd
      - text: "COMM"
        menu:
          - tracks/comm/comm101.qmd
          - tracks/comm/comm102.qmd
          - tracks/comm/comm103.qmd
          - tracks/comm/comm104.qmd
          - tracks/comm/comm201.qmd
          - tracks/comm/comm202.qmd
      - text: "More"
        menu:
          - modules.qmd
          - course-setup.qmd
          - pair-programming.qmd
          - text: Syllabus
            href: https://docs.google.com/document/d/10pUhmBvsWVQyDpV4DIBtkWVghk3rkZAv9Z7wRfSitKs/edit?usp=sharing

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

